#!/bin/sh

SCRIPT_DIR=$(dirname $0)

DEFAULT_TOOLCHAIN_SETS_ARG="--toolchain-sets=gcc3"

# NLS has issues building on Cygwin.
# It’s non-critical, so we will skip it when running under Cygwin.
if [ "$(uname --operating-system)" == "Cygwin" ] ; then
  DISABLE_NLS="--disable-nls"
fi

# Process any command-line arguments
if [ $# -gt 0 ]; then
  ALL_ARGS=$(printf -- '"%s" ' "$@")
fi

for ARG in "$@"; do
  case "$ARG" in
    --toolchain-sets=*)
      unset DEFAULT_TOOLCHAIN_SETS_ARG
      ;;
    --enable-nls | --enable-nls=yes)
      # If enable NLS is specified, ensure the disable argument is removed
      unset DISABLE_NLS
      ;;
    --disable-nls | --enable-nls=no)
      # If disable NLS is already specified, don't double-set the argument
      unset DISABLE_NLS
      ;;
  esac
done

# Enumerate default H8/300 arguments for configure
CONFIGURE_ARGS=" \
  --with-gcc \
  --with-gnu-as \
  --with-gnu-ld \
  --with-newlib \
  --disable-bootstrap \
  --disable-libssp \
  --disable-libada \
  --disable-multilib \
  $DISABLE_NLS \
  --without-gpc-shared \
  --enable-target-optspace \
  --target=h8300-hitachi-coff \
  --enable-targets=h8300-hitachi-coff,h8300-hitachi-elf \
  $DEFAULT_TOOLCHAIN_SETS_ARG \
  $ALL_ARGS"

# For any quoted substrings in variables (such as $ALL_ARGS might have)
#   to be properly processed as a single quoted argument,
#   the command must be eval'd instead of being executed directly.
#   c.f. https://stackoverflow.com/q/39583838/#comment66478321_39583915
eval "$SCRIPT_DIR/configure $CONFIGURE_ARGS"
