#!/bin/sh

# Pre-configured standard options for building a cross compiler
#   targeting the Hitachi H8/300 processor
#
# For a smaller build, consider including the following options:
#   --without-newlib --disable-nls --disable-libstdc__-v3 --disable-sim --disable-gdb
#
# If building GCC3 without GDB, then the following option can also be added:
#   --disable-libdecnumber

SCRIPT_DIR=$(dirname $0)

DEFAULT_TOOLCHAIN_SETS_ARG="--toolchain-sets=gcc3"
DEFAULT_PROGRAM_SUFFIX_CONFIG_ARG="--with-program-suffix"
DEFAULT_NEWLIB="--with-newlib"

# NLS has issues building on Cygwin.
# It’s non-critical, so we will skip it when running under Cygwin.
if [ "$(uname --operating-system)" = "Cygwin" ] ; then
  DEFAULT_NLS="--disable-nls"
fi

# Process any command-line arguments
if [ $# -gt 0 ]; then
  ALL_ARGS=$(printf -- '"%s" ' "$@")
fi

for ARG in "$@"; do
  case "$ARG" in
    --toolchain-sets=*)
      unset DEFAULT_TOOLCHAIN_SETS_ARG
      ;;
    --enable-nls | --enable-nls=yes | --disable-nls | --enable-nls=no)
      # If NLS is explicitly specified, clear the default NLS argument
      unset DEFAULT_NLS
      ;;
    --with-newlib | --without-newlib)
      # If NewLib is explicitly specified, clear the default NewLib argument
      unset DEFAULT_NEWLIB
      ;;
    --with-program-suffix)
      # If a program suffix is already specified, don't double-set the argument
      unset DEFAULT_PROGRAM_SUFFIX_CONFIG_ARG
      ;;
    --without-program-suffix)
      # If without program suffix is  specified, ensure the default "with" argument is removed
      unset DEFAULT_PROGRAM_SUFFIX_CONFIG_ARG
      ;;
  esac
done

# Enumerate default H8/300 arguments for configure
CONFIGURE_ARGS=" \
  --with-gcc \
  --with-gnu-as \
  --with-gnu-ld \
  $DEFAULT_NEWLIB \
  --disable-bootstrap \
  --disable-libssp \
  --disable-libada \
  --disable-multilib \
  $DEFAULT_NLS \
  --without-gpc-shared \
  --enable-target-optspace \
  --target=h8300-hitachi-coff \
  --enable-targets=h8300-hitachi-coff,h8300-hitachi-elf \
  $DEFAULT_TOOLCHAIN_SETS_ARG \
  $ALL_ARGS"

# For any quoted substrings in variables (such as $ALL_ARGS might have)
#   to be properly processed as a single quoted argument,
#   the command must be eval'd instead of being executed directly.
#   c.f. https://stackoverflow.com/q/39583838/#comment66478321_39583915
eval "$SCRIPT_DIR/configure $CONFIGURE_ARGS"
