name: GNU Legacy Toolchain CI

on:
  workflow_dispatch:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

env:
  UBUNTU_BUILD_DEPENDS: autoconf autopoint automake m4 make binutils gcc g++ gcc-multilib bison flex libtool gawk gettext texinfo file libisl-dev dejagnu  stow
  # after adding i386 multiarch via `sudo dpkg --add-architecture i386`
  UBUNTU_MULTIARCH_i386_BUILD_DEPENDS:  libc6:i386 libc6-dev:i386 linux-libc-dev:i386
  
  openSUSE_BUILD_DEPENDS: autoconf gettext-tools automake m4 make binutils gcc gcc-c++ gcc-objc glibc-devel glibc-devel-32bit bison flex libtool gawk gettext-runtime texinfo file libisl23 dejagnu  stow
  # libisl23, which is a version-specific package of ISL, appeasrs to be included as a dependency of other package(s)
  
  # If these older source package releases will not build without disabling Fortify and/or run without buffer overflow errors,
  #    then "make CPPFLAGS=-U_FORTIFY_SOURCE" might be necessary
  #    Passing that to this older configure might not work, as should otherwise seem doable per
  #    the link https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html
  CROSS_TARGET: h8300-hitachi-coff

  BUILD_DIR_GCC: build/gcc
  BUILD_DIR_GPC: build/gpc
  BUILD_DIR_GDB: build/gdb
  SYSROOT_DIR:   sysroot
  
  STOW_PACKAGE_NAME: h8300-hitachi-coff-toolchain
  TOOLCHAIN_INSTALL_NAME: h8300-hitachi-coff-toolchain_install

jobs:
  build_cross_toolchain_job:
    name:     Full H8/300 Cross-Toolchain Build & Install
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    
    steps:
    - name: Get latest from version control
      uses: actions/checkout@v4
      #with:
        # git-restore-mtime-bare uses the ref log to find the correct timestamp
        # for each file. This requires a full git history. The default value (1)
        # creates a shallow checkout.
        # fetch-depth: 0

      # Fix timestamps (needed to prevent gcc/c-parse.c from sometimes being regenerated during build)
    #- name: Restore source timestamps
      #uses: chetan/git-restore-mtime-action@v2

    - name: Update build environment
      run:  sudo apt-get --assume-yes update

    - name: Install build dependencies
      run:  sudo apt-get --assume-yes install $UBUNTU_BUILD_DEPENDS

    - name: Setup the build directory for an H8/300 cross-toolchain
      run:  mkdir -p $BUILD_DIR_GCC


    # Run the build steps
    - name: Configure the build for an H8/300 cross-toolchain
      run:  |
        cd $BUILD_DIR_GCC
        echo "Current working directory: $PWD"
        ../../src-combined/$CROSS_TARGET-configure  --prefix=$GITHUB_WORKSPACE/$SYSROOT_DIR

    - name: Execute the build for a GCC H8/300 cross-compiler
      run:  |
        cd $BUILD_DIR_GCC
        echo "Current working directory: $PWD"
        make --keep-going

    - name: Test install the built GCC H8/300 cross-compiler to a sysroot
      run:  |
        cd $BUILD_DIR_GCC
        echo "Current working directory: $PWD"
        sudo make install

    # Before archiving, tar the host installation output to preserve file permission
    # c.f. https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
    # To avoid including a "." or other unwanted directory, c.f. https://stackoverflow.com/a/39530409
    - name: Tar the host installation snapshot to preserve file permissions
      run:  find $SYSROOT_DIR -printf "%P\n" | sort | tar --verbose --create --file build/${{ env.TOOLCHAIN_INSTALL_NAME }}.tar --no-recursion --directory=$SYSROOT_DIR --files-from=-

    - name: Archive the host installation snapshot tar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.TOOLCHAIN_INSTALL_NAME }}_[runner~${{ matrix.os }}]_run${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
        path: build/${{ env.TOOLCHAIN_INSTALL_NAME }}.tar

    - name: Install the built GCC H8/300 cross-compiler using Stow
      run:  |
        cd $BUILD_DIR_GCC
        echo "Current working directory: $PWD"
        sudo make stow

    - name: Check always if any version-controlled files were modified
      if:   always()
      run:  git status

    - name: Show always any diffs of version-controlled files
      if:   always()
      run:  git diff


  # For quicker continuous integration feedback, run just the GCC build as a job
  build_cross_gcc_job:
    name:     Build GCC for the H8/300
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    
    steps:
    - name: Get latest from version control
      uses: actions/checkout@v4

    - name: Update build environment
      run:  sudo apt-get --assume-yes update

    - name: Install build dependencies
      run:  sudo apt-get --assume-yes install $UBUNTU_BUILD_DEPENDS

    - name: Setup the build directory for an H8/300 cross-toolchain
      run:  mkdir -p $BUILD_DIR_GCC


    # Run the build steps
    - name: Configure the build for an H8/300 cross-toolchain
      run:  |
        cd $BUILD_DIR_GCC
        echo "Current working directory: $PWD"
        ../../src-combined/$CROSS_TARGET-configure  --prefix=$GITHUB_WORKSPACE/$SYSROOT_DIR

    - name: Execute the build for a GCC H8/300 cross-compiler
      run:  |
        cd $BUILD_DIR_GCC/gcc-combined
        echo "Current working directory: $PWD"
        make --keep-going


  # For quicker continuous integration feedback, run just the GDB build as a job
  build_cross_gdb_job:
    name:     Build GDB for the H8/300
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    
    steps:
    - name: Get latest from version control
      uses: actions/checkout@v4

    - name: Update build environment
      run:  sudo apt-get --assume-yes update

    - name: Install build dependencies
      run:  sudo apt-get --assume-yes install $UBUNTU_BUILD_DEPENDS

    - name: Setup the build directory for an H8/300 cross-toolchain
      run:  mkdir -p $BUILD_DIR_GCC


    # Run the build steps
    - name: Configure the build for an H8/300 cross-toolchain
      run:  |
        cd $BUILD_DIR_GCC
        echo "Current working directory: $PWD"
        ../../src-combined/$CROSS_TARGET-configure  --prefix=$GITHUB_WORKSPACE/$SYSROOT_DIR

    - name: Execute the build for a GDB H8/300 debugger
      run:  |
        cd $BUILD_DIR_GCC/gdb
        echo "Current working directory: $PWD"
        make --keep-going



#  build_native_job:
#    name:     Build a native compiler (non-cross-compiling)
#    runs-on:  ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ ubuntu-latest ]
#
#    steps:
#    - name: Get latest from version control
#      uses: actions/checkout@v4
#      with:
#        # git-restore-mtime-bare uses the ref log to find the correct timestamp
#        # for each file. This requires a full git history. The default value (1)
#        # creates a shallow checkout.
#        fetch-depth: 0
#
#      # Fix timestamps
#    - name: Restore source timestamps
#      uses: chetan/git-restore-mtime-action@v2
#
#    - name: Update build environment
#      run:  sudo apt-get --assume-yes update
#
#    - name: Install build dependencies
#      run:  sudo apt-get --assume-yes install $UBUNTU_BUILD_DEPENDS
#
#    - name: Setup the build folders for a native gcc+binutils+gpc compiler
#      run:  mkdir -p $BUILD_DIR_GPC
#
#    - name: Configure the build for a native gcc+binutils+gpc compiler
#      run:  |
#        cd $BUILD_DIR_GPC
#        echo "Current working directory: $PWD"
#        ../../src-combined/gcc-combined/configure  --prefix=$GITHUB_WORKSPACE/$SYSROOT_DIR  --program-suffix=3
#
#    - name: Execute the build for a native gcc+binutils+gpc compiler
#      run:  |
#        cd $BUILD_DIR_GPC
#        echo "Current working directory: $PWD"
#        make --keep-going
#
#    - name: Test install the built native gcc+binutils+gpc compiler
#      run:  |
#        cd $BUILD_DIR_GPC
#        echo "Current working directory: $PWD"
#        make DESTDIR=$GITHUB_WORKSPACE/$SYSROOT_DIR install
#
#    # Before archiving, tar the host installation output to preserve file permission
#    # c.f. https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
#    # To avoid including a "." or other unwanted directory, c.f. https://stackoverflow.com/a/39530409
#    - name: Tar the host installation snapshot to preserve file permissions
#      run:  find $SYSROOT_DIR -printf "%P\n" | sort | tar --verbose --create --file build/native-gpc_install.tar --no-recursion --directory=$SYSROOT_DIR --files-from=-
#
#    - name: Archive the host installation snapshot tar file
#      uses: actions/upload-artifact@v4
#      with:
#        name: native-gpc_install_[runner~${{ matrix.os }}]_run${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
#        path: build/native-gpc_install.tar
#
#    - name: Install the built native gcc+binutils+gpc compiler
#      run:  |
#        cd $BUILD_DIR_GPC
#        echo "Current working directory: $PWD"
#        sudo make install
